#!/usr/bin/env python3
"""
make-taxonomy-cast.py — synthesize demo/taxonomy.cast with deliberate pacing.

Why synthesize instead of `asciinema rec`: in a headless/CI shell there is no TTY,
and asciinema's headless recorder does not honor real `sleep` timing, so the GIF
races by. Building the cast file directly gives frame-exact control over every
pause, a real typewriter effect, and colored emphasis — and embeds the AUTHENTIC
bytes captured from the real tools (see /tmp/cap/*, regenerated by the README cmd).

Output: asciinema v2 cast on stdout.  Render:  agg --theme asciinema cast gif
"""
import json, sys, os
from castkit import *

CAP = os.environ.get("CAP", "/tmp/cap")   # dir of captured bytes (see record-taxonomy.sh)
W, H = 92, 32

# overrides — this cast's voiceover reads a touch slower and its prompt/typing differ:
def vo(s, hold=1.7):
    """voiceover narration line — dim, with reading time proportional to length."""
    emit(DIM + s + RST + "\r\n")
    wait(max(hold, 0.045 * len(s)))

def typed(cmd, dt=0.034, pre=0.4, post=0.6):
    """type a shell command after a green prompt, char by char."""
    wait(pre)
    emit(GRN + "❯ " + RST)
    for i, ch in enumerate(cmd):
        emit(ch)
        # tiny deterministic rhythm variation, no RNG
        wait(dt + (0.03 if ch == " " else 0.0) + (0.012 if i % 7 == 3 else 0.0))
    emit("\r\n")
    wait(post)

def raw(path, indent="", recolor=None):
    """print authentic captured bytes; optional per-line recolor(line)->line."""
    for ln in open(path).read().splitlines():
        out = recolor(ln) if recolor else ln
        emit(indent + out + "\r\n")
        wait(0.06)

# ── colorizer for the finding block ─────────────────────────────────────────────
def color_finding(ln):
    s = ln
    if "search.tsx:27" in s and "rule" not in s:
        return BLD + WHT + s + RST
    if s.strip() == "search.tsx":
        return BLD + WHT + s + RST
    if "enforce/input-no-name" in s:
        s = s.replace("enforce/input-no-name", MAG + "enforce/input-no-name" + RST + DIM)
        s = s.replace("[block]", RED + BLD + "[block]" + RST + DIM)
        s = s.replace("(call-site content check)", CYN + BLD + "(call-site content check)" + RST + DIM)
        return DIM + s + RST
    if "wcag:" in s:
        return DIM + s.replace("WCAG 1.3.1", WHT + "WCAG 1.3.1" + DIM).replace("WCAG 3.3.2", WHT + "WCAG 3.3.2" + DIM) + RST
    if "severity:" in s:
        return DIM + s.replace("CRITICAL", RED + BLD + "CRITICAL" + RST + DIM) + RST
    if "corpus:" in s:
        return DIM + s.replace("[VERY COMMON]", YEL + "[VERY COMMON]" + DIM).replace("22/26 orgs", YEL + BLD + "22/26 orgs" + RST + DIM) + RST
    if "fix:" in s:
        return GRN + s + RST
    return DIM + s + RST

# ══ THE STORY ══════════════════════════════════════════════════════════════════
clearscreen()
wait(0.3)
line(BLD + CYN + "  a11y-checker" + RST)
wait(0.6)
line(DIM + "  what 26 real accessibility audits taught us — and where it showed up next" + RST)
wait(2.6)
clearscreen(); wait(0.3)

# 1 — the human stake
line(MAG + BLD + "  ┄┄ the bug that kept coming back ┄┄" + RST); blank(1); wait(0.8)
vo("  Across 26 real audits, one failure showed up more than any other:")
vo("  a search box a screen reader cannot name.")
wait(0.4)
vo("  You see a box that says “Search documentation…”")
vo("  A blind user tabs to it and hears: “edit, blank.”  No idea what it's for.")
wait(0.5)
vo("  " + YEL + "22 of those 26 organizations shipped this exact bug." + RST, hold=2.4)
wait(1.0)
clearscreen(); wait(0.3)

# 2 — the twist
line(MAG + BLD + "  ┄┄ then we pointed it at shadcn/ui ┄┄" + RST); blank(1); wait(0.8)
vo("  taxonomy — shadcn's own example app. ~25k stars.")
vo("  The code thousands of React devs copy from. Here's its search box:")
blank(1)
typed("sed -n '22,33p' tax/components/search.tsx")
raw(CAP + "/source.txt", indent="  " + BLU)
emit(RST); blank(1); wait(1.2)
vo("  There it is again. A shadcn " + WHT + "<Input>" + DIM + ", a placeholder — and no label.")
wait(1.4)
clearscreen(); wait(0.3)

# 3 — the incumbent passes
line(MAG + BLD + "  ┄┄ the linter everyone already runs ┄┄" + RST); blank(1); wait(0.8)
vo("  eslint-plugin-jsx-a11y, recommended config. The check most teams have.")
blank(1)
typed("npx eslint --config jsx-a11y tax/components/search.tsx", post=1.0)
line("  " + GRN + BLD + "✓  0 problems" + RST + DIM + "   eslint says it's clean." + RST)
wait(1.8)
vo("  Clean — because " + WHT + "<Input>" + DIM + " is a component, and eslint can't look inside it.")
wait(1.6)
clearscreen(); wait(0.3)

# 4 — the catch
line(MAG + BLD + "  ┄┄ a11y-checker, the very same file ┄┄" + RST); blank(1); wait(0.8)
vo("  It resolves " + WHT + "<Input>" + DIM + " down to a real " + WHT + "<input>" + DIM + ", then reads the call site.")
blank(1)
typed("a11y check tax/components", post=0.8)
raw(CAP + "/finding_color.txt", indent="  ", recolor=color_finding)
emit(RST); blank(1); wait(2.2)
vo("  " + CYN + "(call-site content check)" + DIM + " — that's the line eslint can't produce.")
wait(1.6)
clearscreen(); wait(0.3)

# 5 — close, land the soul
blank(1)
line(BLD + WHT + "  One line of config taught it your design system." + RST); wait(1.6)
line(BLD + WHT + "  Now the bug 22 orgs missed never reaches your users." + RST); wait(2.0)
blank(1)
line("  " + DIM + "eslint:" + RST + " clean    " + DIM + "·" + RST + "    " + CYN + BLD + "a11y-checker:" + RST + " caught it, ranked it, handed you the fix.")
wait(3.0)

# ── write cast ──────────────────────────────────────────────────────────────────
write_cast(events, W, H)
